spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:./storage-db'
  jpa:
    hibernate:
      ddl-auto: validate
server:
  servlet:
    context-path: '/home'
management:
  endpoints:
    web:
      exposure:
        include: '*'
